services:
  api:
    image: cicd102
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    env_file:
      - backend/.env
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
