services:
  api:
    image: cicd102
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - '3000:3000'

    env_file:
      - backend/.env
  frontend:
    image: picnigram-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
